// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCajXPZ9rnbCHCgUhIwzm8xZ5XzOGZYJNY',
    appId: '1:758436208904:web:aa093e8071794879b90cbd',
    messagingSenderId: '758436208904',
    projectId: 'p2p-997a1',
    authDomain: 'p2p-997a1.firebaseapp.com',
    storageBucket: 'p2p-997a1.appspot.com',
    measurementId: 'G-XZW27LVFSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX6IITSPq399OD7TD9M-rnN81CX_YNFkc',
    appId: '1:758436208904:android:4d0d6176f18ad42bb90cbd',
    messagingSenderId: '758436208904',
    projectId: 'p2p-997a1',
    storageBucket: 'p2p-997a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTwAliENFHZm7IIfUqrxlqN2ZgEfT8Aa8',
    appId: '1:758436208904:ios:06f863bfc5b5aaa4b90cbd',
    messagingSenderId: '758436208904',
    projectId: 'p2p-997a1',
    storageBucket: 'p2p-997a1.appspot.com',
    iosClientId: '758436208904-m8fgudre65h9pq5a2css5m14etv8tlh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordManager',
  );
}
